FROM debian:bookworm-slim
ARG TARGETARCH
WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata ca-certificates wget && \
    ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/db /app/logs /app/template /app/plugins && \
    chmod 777 /app/db /app/logs /app/template /app/plugins

COPY build/subflow-linux-${TARGETARCH} /app/subflow
COPY static /app/static
RUN chmod +x /app/subflow

EXPOSE 8000
CMD ["/app/subflow"]
